//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doro.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Doro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Doro() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("doro.Localization.Doro", typeof(Doro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adolf Tower ähnelt.
        /// </summary>
        internal static string AdolfTower {
            get {
                return ResourceManager.GetString("AdolfTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1/matching Village edge ähnelt.
        /// </summary>
        internal static string AdolfTower_Descr {
            get {
                return ResourceManager.GetString("AdolfTower_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balloon Launch Site ähnelt.
        /// </summary>
        internal static string Balloon {
            get {
                return ResourceManager.GetString("Balloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2/distance ähnelt.
        /// </summary>
        internal static string Balloon_Descr {
            get {
                return ResourceManager.GetString("Balloon_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base ähnelt.
        /// </summary>
        internal static string BasePack {
            get {
                return ResourceManager.GetString("BasePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Circus ähnelt.
        /// </summary>
        internal static string Circus {
            get {
                return ResourceManager.GetString("Circus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die completely surrounded = 10 ähnelt.
        /// </summary>
        internal static string Circus_Descr {
            get {
                return ResourceManager.GetString("Circus_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Construction Site ähnelt.
        /// </summary>
        internal static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die per territory 7+ = 7 ähnelt.
        /// </summary>
        internal static string Construction_Descr {
            get {
                return ResourceManager.GetString("Construction_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Board Game ähnelt.
        /// </summary>
        internal static string Dorfromantik_BaseGame {
            get {
                return ResourceManager.GetString("Dorfromantik_BaseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flags ähnelt.
        /// </summary>
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest ähnelt.
        /// </summary>
        internal static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest Cabin ähnelt.
        /// </summary>
        internal static string ForestCabin {
            get {
                return ResourceManager.GetString("ForestCabin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest-Tasks ähnelt.
        /// </summary>
        internal static string ForestCabin_Descr {
            get {
                return ResourceManager.GetString("ForestCabin_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Golden Heart ähnelt.
        /// </summary>
        internal static string GoldenHeart {
            get {
                return ResourceManager.GetString("GoldenHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2/matching edge ähnelt.
        /// </summary>
        internal static string GoldenHeart_Descr {
            get {
                return ResourceManager.GetString("GoldenHeart_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grain ähnelt.
        /// </summary>
        internal static string Grain {
            get {
                return ResourceManager.GetString("Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harbor ähnelt.
        /// </summary>
        internal static string Harbor {
            get {
                return ResourceManager.GetString("Harbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die closed off = 1/tile ähnelt.
        /// </summary>
        internal static string Harbor_Descr {
            get {
                return ResourceManager.GetString("Harbor_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harvest Festival ähnelt.
        /// </summary>
        internal static string HarvestFestival {
            get {
                return ResourceManager.GetString("HarvestFestival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grain-Tasks ähnelt.
        /// </summary>
        internal static string HarvestFestival_Descr {
            get {
                return ResourceManager.GetString("HarvestFestival_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hill ähnelt.
        /// </summary>
        internal static string Hill {
            get {
                return ResourceManager.GetString("Hill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die at distance 2 = 2/Task tile ähnelt.
        /// </summary>
        internal static string Hill_Descr {
            get {
                return ResourceManager.GetString("Hill_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locomotive ähnelt.
        /// </summary>
        internal static string Locomotive {
            get {
                return ResourceManager.GetString("Locomotive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track-Tasks ähnelt.
        /// </summary>
        internal static string Locomotive_Descr {
            get {
                return ResourceManager.GetString("Locomotive_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longest Stream ähnelt.
        /// </summary>
        internal static string LongestStream {
            get {
                return ResourceManager.GetString("LongestStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Longest Track ähnelt.
        /// </summary>
        internal static string LongestTrack {
            get {
                return ResourceManager.GetString("LongestTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Great Mill ähnelt.
        /// </summary>
        internal static string Mill {
            get {
                return ResourceManager.GetString("Mill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die at distance 2 = 2/Task + 2/Flag ähnelt.
        /// </summary>
        internal static string Mill_Descr {
            get {
                return ResourceManager.GetString("Mill_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pegasus ähnelt.
        /// </summary>
        internal static string Pegasus {
            get {
                return ResourceManager.GetString("Pegasus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1/matching Forest edge ähnelt.
        /// </summary>
        internal static string Pegasus_Descr {
            get {
                return ResourceManager.GetString("Pegasus_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red Hearts ähnelt.
        /// </summary>
        internal static string RedHearts {
            get {
                return ResourceManager.GetString("RedHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1/matching edge ähnelt.
        /// </summary>
        internal static string RedHearts_Descr {
            get {
                return ResourceManager.GetString("RedHearts_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shepherdess ähnelt.
        /// </summary>
        internal static string Shepherdess {
            get {
                return ResourceManager.GetString("Shepherdess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1/Sheep ähnelt.
        /// </summary>
        internal static string Shepherdess_Descr {
            get {
                return ResourceManager.GetString("Shepherdess_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ship ähnelt.
        /// </summary>
        internal static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream-Tasks ähnelt.
        /// </summary>
        internal static string Ship_Descr {
            get {
                return ResourceManager.GetString("Ship_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signalman ähnelt.
        /// </summary>
        internal static string Signalman {
            get {
                return ResourceManager.GetString("Signalman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2/Grade Crossing ähnelt.
        /// </summary>
        internal static string Signalman_Descr {
            get {
                return ResourceManager.GetString("Signalman_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream ähnelt.
        /// </summary>
        internal static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks ähnelt.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track ähnelt.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Train Station ähnelt.
        /// </summary>
        internal static string Trainstation {
            get {
                return ResourceManager.GetString("Trainstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die closed off = 1/tile ähnelt.
        /// </summary>
        internal static string Trainstation_Descr {
            get {
                return ResourceManager.GetString("Trainstation_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TV Tower ähnelt.
        /// </summary>
        internal static string TvTower {
            get {
                return ResourceManager.GetString("TvTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1/matching Grain edge ähnelt.
        /// </summary>
        internal static string TvTower_Descr {
            get {
                return ResourceManager.GetString("TvTower_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocked ähnelt.
        /// </summary>
        internal static string Unlockables {
            get {
                return ResourceManager.GetString("Unlockables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Village ähnelt.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watchtower ähnelt.
        /// </summary>
        internal static string Watchtower {
            get {
                return ResourceManager.GetString("Watchtower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Village-Tasks ähnelt.
        /// </summary>
        internal static string Watchtower_Descr {
            get {
                return ResourceManager.GetString("Watchtower_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wetterau ähnelt.
        /// </summary>
        internal static string Wetterau {
            get {
                return ResourceManager.GetString("Wetterau", resourceCulture);
            }
        }
    }
}
